version: '3.8'

services:
  postgres-app:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: admin
      POSTGRES_DB: realestate
    ports:
      - 5432:5432
    volumes:
      - app_data:/var/lib/postgresql/data_app

volumes:
  app_data:
